spring.datasource.url=jdbc:postgresql://localhost:5432/wolfpackunity
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.org.jooq.tools.LoggerListener=DEBUG
spring.security.oauth2.client.registration.google.client-id=dev-client-id
spring.security.oauth2.client.registration.google.client-secret=dev-client-secret
server.port=8081
