spring.datasource.url=jdbc:postgresql://localhost:5433/wolfpackunity
spring.datasource.username=gym
spring.datasource.password=gym
logging.level.org.jooq.tools.LoggerListener=DEBUG
spring.security.oauth2.client.registration.google.client-id=dev-client-id
spring.security.oauth2.client.registration.google.client-secret=dev-client-secret
